/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmobil;

import Database.KoneksiDatabase;
import Database.ResultSetTable;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static rentalmobil.SewaMobil.getTanggalFromTable;

/**
 *
 * @author zulfi
 */
public class cetak extends javax.swing.JFrame {

    /**
     * Creates new form cetak
     */
    ResultSet rs;
    KoneksiDatabase con;
   

    public cetak() {
        initComponents();
        con = new KoneksiDatabase(new Database.Parameter().HOST_DB, new Database.Parameter().USERNAME_DB, new Database.Parameter().PASSWORD_DB);
      
        jPanel2.setBackground(new Color(0,0,0,200));
        loadTabel();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_tglpemin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_pengem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_lamam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_supir = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_lamas = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nopol1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_harga1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nama1 = new javax.swing.JTextField();
        txt_alamat1 = new javax.swing.JTextField();
        txt_tipe1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnPV = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_print = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tgl peminjaman");

        txt_tglpemin.setEditable(false);
        txt_tglpemin.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        txt_tglpemin.setPreferredSize(new java.awt.Dimension(6, 30));

        jLabel8.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tgl Pengembalian");

        txt_pengem.setEditable(false);
        txt_pengem.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        txt_pengem.setPreferredSize(new java.awt.Dimension(6, 30));

        jLabel9.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lama Sewa mobil");

        txt_lamam.setEditable(false);
        txt_lamam.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        txt_lamam.setPreferredSize(new java.awt.Dimension(6, 30));

        jLabel10.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Supir");

        txt_supir.setEditable(false);
        txt_supir.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        txt_supir.setPreferredSize(new java.awt.Dimension(6, 30));

        jLabel11.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lama Sewa Supir");

        txt_lamas.setEditable(false);
        txt_lamas.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        txt_lamas.setPreferredSize(new java.awt.Dimension(6, 30));
        txt_lamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lamasActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total");

        txt_total.setEditable(false);
        txt_total.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        txt_total.setPreferredSize(new java.awt.Dimension(6, 30));
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No polisi");

        txt_nopol1.setEditable(false);
        txt_nopol1.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        txt_nopol1.setPreferredSize(new java.awt.Dimension(6, 30));

        jLabel6.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga");

        txt_harga1.setEditable(false);
        txt_harga1.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        txt_harga1.setPreferredSize(new java.awt.Dimension(6, 30));

        jLabel12.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama");

        jLabel13.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Alamat");

        jLabel4.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipe mobil");

        txt_nama1.setEditable(false);
        txt_nama1.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        txt_nama1.setPreferredSize(new java.awt.Dimension(6, 30));

        txt_alamat1.setEditable(false);
        txt_alamat1.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        txt_alamat1.setPreferredSize(new java.awt.Dimension(6, 30));

        txt_tipe1.setEditable(false);
        txt_tipe1.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        txt_tipe1.setPreferredSize(new java.awt.Dimension(6, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(txt_nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(txt_alamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(txt_tipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(txt_nopol1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(txt_harga1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txt_tglpemin, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txt_pengem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addComponent(txt_lamas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(txt_supir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(txt_lamam, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txt_nama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_alamat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_tipe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_nopol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_harga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_tglpemin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_pengem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txt_lamam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_supir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 80, 400, 470);

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(427, 277, 610, 407);

        jLabel1.setFont(new java.awt.Font("Quicksand Medium", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cetak Bukti Sewa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 20, 380, 45);

        btnPV.setFont(new java.awt.Font("Quicksand Medium", 1, 18)); // NOI18N
        btnPV.setText("Print View");
        btnPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPVActionPerformed(evt);
            }
        });
        jPanel1.add(btnPV);
        btnPV.setBounds(57, 580, 130, 40);

        btnPrint.setFont(new java.awt.Font("Quicksand Medium", 1, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint);
        btnPrint.setBounds(230, 580, 140, 40);

        btnKeluar.setFont(new java.awt.Font("Quicksand Medium", 1, 18)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back.png"))); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar);
        btnKeluar.setBounds(30, 20, 30, 30);

        tb_print.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_printMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_print);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(427, 83, 860, 176);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jaz.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1370, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPVActionPerformed
        // TODO add your handling code here:

        area.setText("**********************************************************************************************************************\n");
        area.setText(area.getText() + "\t\t          BUKTI SEWA MOBIL \n");
        area.setText(area.getText() + "**********************************************************************************************************************\n");
        area.setText(area.getText() + "\n\tNama\t\t = " + txt_nama1.getText() + "\n");
        area.setText(area.getText() + "\n\tAlamat\t\t = " + txt_alamat1.getText() + "\n");
        area.setText(area.getText() + "\n\tTipe Mobil\t\t = " + txt_tipe1.getText() + "\n");
        area.setText(area.getText() + "\n\tNo Polisi\t\t = " + txt_nopol1.getText() + "\n");
        area.setText(area.getText() + "\n\tHarga\t\t = " + txt_harga1.getText() + "\n");
        area.setText(area.getText() + "\n\tTgl Peminjaman\t = " + txt_tglpemin.getText() + "\n");
        area.setText(area.getText() + "\n\tTgl Pengembalian\t = " + txt_pengem.getText() + "\n");
        area.setText(area.getText() + "\n\tLama Mobil\t\t = " + txt_lamam.getText() + "\n");
        area.setText(area.getText() + "\n\tSupir\t\t = " + txt_supir.getText() + "\n");
        area.setText(area.getText() + "\n\tLama Supir\t\t = " + txt_lamas.getText() + "\n");
        area.setText(area.getText() + "\n\tTotal\t\t = " + txt_total.getText() + "\n");
        area.setText(area.getText() + "**********************************************************************************************************************\n\n");
        area.setText(area.getText() + "\n\n\n\t                 Terima kasih Telah Menyewa Mobil di Sewa Mobil Hiace\n");
    }//GEN-LAST:event_btnPVActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            area.print();
            JOptionPane.showMessageDialog(null, "Tiket behasil di cetak");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tb_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_printMouseClicked

        txt_nama1.setText(String.valueOf(tb_print.getValueAt(tb_print.getSelectedRow(), 1)));
        txt_alamat1.setText(String.valueOf(tb_print.getValueAt(tb_print.getSelectedRow(), 2)));

        txt_tipe1.setText(String.valueOf(tb_print.getValueAt(tb_print.getSelectedRow(), 4)));

        txt_nopol1.setText(String.valueOf(tb_print.getValueAt(tb_print.getSelectedRow(), 5)));

        txt_harga1.setText(String.valueOf(tb_print.getValueAt(tb_print.getSelectedRow(), 6)));

        txt_lamam.setText(String.valueOf(tb_print.getValueAt(tb_print.getSelectedRow(), 9)));

        txt_supir.setText(String.valueOf(tb_print.getValueAt(tb_print.getSelectedRow(), 10)));

        txt_tglpemin.setText(String.valueOf(tb_print.getValueAt(tb_print.getSelectedRow(), 7)));
        txt_pengem.setText(String.valueOf(tb_print.getValueAt(tb_print.getSelectedRow(), 8)));

        txt_lamas.setText(String.valueOf(tb_print.getValueAt(tb_print.getSelectedRow(), 11)));
        txt_total.setText(String.valueOf(tb_print.getValueAt(tb_print.getSelectedRow(), 12)));
    }//GEN-LAST:event_tb_printMouseClicked

    private void txt_lamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lamasActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cetak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPV;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_print;
    private javax.swing.JTextField txt_alamat1;
    private javax.swing.JTextField txt_harga1;
    private javax.swing.JTextField txt_lamam;
    private javax.swing.JTextField txt_lamas;
    private javax.swing.JTextField txt_nama1;
    private javax.swing.JTextField txt_nopol1;
    private javax.swing.JTextField txt_pengem;
    private javax.swing.JTextField txt_supir;
    private javax.swing.JTextField txt_tglpemin;
    private javax.swing.JTextField txt_tipe1;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

    private void loadTabel() {
        String namaKolom[] = {"NIK", "Nama", "Alamat", "No_telp", "Tipe_mobil", "No_polisi", "harga", "Tgl_peminjaman", "Tgl_pengembalian", "Lama_mobil", "Supir", "Lama_supir", "Total"}; //,
        rs = con.querySelect(namaKolom, "sewa_mobil");
        tb_print.setModel(new ResultSetTable(rs)); //,"tgl_pinjam","tgl_kembali" ,jDateChooser1.getDateFormatString(),jDateChooser2.getDateFormatString()
    }
}
