/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmobil;

import Database.KoneksiDatabase;
import Database.ResultSetTable;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author zulfi
 */
public class SewaMobil extends javax.swing.JFrame {
 ResultSet rs;
    KoneksiDatabase con;
    static String nama;
    static String nik;
    static String alamat;
    static String tlp;
    static String email;
    String status1;
    
    /**
     * Creates new form SewaMobil
     */
    public SewaMobil() {
        initComponents();
        jPanel2.setBackground(new Color(0,0,0,200));
        jPanel3.setBackground(new Color(0,0,0,200));
        jPanel4.setBackground(new Color(0,0,0,200));
        
        con = new KoneksiDatabase(new Database.Parameter().HOST_DB, new Database.Parameter().USERNAME_DB, new Database.Parameter().PASSWORD_DB);
        
        loadMobil();
        loadTabel();
        loadSupir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nik = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_notelp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButtonprint = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonSewa = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_lamaPinjam = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_lamaSupir = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cb_Supir = new javax.swing.JComboBox<>();
        btn_hitung = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        lb_total = new javax.swing.JLabel();
        jDatetglpengembalian = new com.toedter.calendar.JDateChooser();
        jDatetglpeminjaman1 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cb_mobil = new javax.swing.JComboBox<>();
        cb_Nopolisi = new javax.swing.JComboBox<>();
        lb_Merek = new javax.swing.JLabel();
        lb_Tahun = new javax.swing.JLabel();
        lb_Harga = new javax.swing.JLabel();
        lb_Status = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_sewa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Quicksand Medium", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Peminjam");

        jLabel4.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIK");

        jLabel5.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");

        jLabel6.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama");

        txt_nik.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N

        txt_nama.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_notelp.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. Telp");

        txt_alamat.setColumns(20);
        txt_alamat.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(txt_notelp)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(txt_nik))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 70, 410, 320);

        jLabel2.setFont(new java.awt.Font("Quicksand Medium", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SEWA MOBIL");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 10, 330, 62);

        jButtonprint.setBackground(new java.awt.Color(255, 255, 255));
        jButtonprint.setFont(new java.awt.Font("Quicksand Medium", 1, 24)); // NOI18N
        jButtonprint.setText("Print");
        jButtonprint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonprintActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonprint);
        jButtonprint.setBounds(670, 660, 160, 40);

        jButtonEdit.setBackground(new java.awt.Color(0, 204, 51));
        jButtonEdit.setFont(new java.awt.Font("Quicksand Medium", 1, 24)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEdit.setText("Edit");
        jButtonEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEdit);
        jButtonEdit.setBounds(850, 660, 160, 40);

        jButtonSewa.setBackground(new java.awt.Color(51, 0, 255));
        jButtonSewa.setFont(new java.awt.Font("Quicksand Medium", 1, 24)); // NOI18N
        jButtonSewa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSewa.setText("Sewa Mobil");
        jButtonSewa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSewaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSewa);
        jButtonSewa.setBounds(1030, 660, 190, 40);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 10, 30, 30);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tanggal Peminjaman");

        jLabel9.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal Pengembalian");

        jLabel10.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lama Peminjaman");

        jLabel11.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Supir");

        jLabel12.setFont(new java.awt.Font("Quicksand Medium", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total :");

        jLabel13.setFont(new java.awt.Font("Quicksand Medium", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Rp.");

        txt_lamaPinjam.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        txt_lamaPinjam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_lamaPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lamaPinjamActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Hari");

        jLabel22.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Lama Supir");

        txt_lamaSupir.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        txt_lamaSupir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_lamaSupir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lamaSupirActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Hari");

        cb_Supir.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        cb_Supir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih Supir" }));
        cb_Supir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_SupirActionPerformed(evt);
            }
        });

        btn_hitung.setBackground(new java.awt.Color(255, 255, 255));
        btn_hitung.setFont(new java.awt.Font("Quicksand Medium", 1, 24)); // NOI18N
        btn_hitung.setText("Hitung");
        btn_hitung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Quicksand Medium", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Transaksi");

        lb_total.setBackground(new java.awt.Color(0, 0, 0));
        lb_total.setFont(new java.awt.Font("Quicksand Medium", 1, 36)); // NOI18N
        lb_total.setForeground(new java.awt.Color(255, 255, 255));
        lb_total.setText("0000");

        jDatetglpengembalian.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N

        jDatetglpeminjaman1.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel10)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(txt_lamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel14))
                        .addComponent(jDatetglpeminjaman1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDatetglpengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_lamaSupir, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23))
                    .addComponent(jLabel22)
                    .addComponent(jLabel11)
                    .addComponent(btn_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Supir, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(177, 177, 177))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lb_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDatetglpeminjaman1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_Supir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel22))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jDatetglpengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_lamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_lamaSupir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(450, 70, 890, 320);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel15.setFont(new java.awt.Font("Quicksand Medium", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mobil");

        jLabel16.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tipe Mobil          :");

        jLabel17.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Merk Mobil         :");

        jLabel18.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("No. Polisi            :");

        jLabel19.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Th Mobil             :");

        jLabel20.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Harga(perhari) :");

        jLabel21.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Status                :");

        cb_mobil.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        cb_mobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih Tipe Mobil" }));
        cb_mobil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_mobilItemStateChanged(evt);
            }
        });
        cb_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mobilActionPerformed(evt);
            }
        });

        cb_Nopolisi.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        cb_Nopolisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih No. Polisi" }));
        cb_Nopolisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_NopolisiActionPerformed(evt);
            }
        });

        lb_Merek.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        lb_Merek.setForeground(new java.awt.Color(255, 255, 255));
        lb_Merek.setText("Merk");

        lb_Tahun.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        lb_Tahun.setForeground(new java.awt.Color(255, 255, 255));
        lb_Tahun.setText("th mobil");

        lb_Harga.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        lb_Harga.setForeground(new java.awt.Color(255, 255, 255));
        lb_Harga.setText("Harga");

        lb_Status.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        lb_Status.setForeground(new java.awt.Color(255, 255, 255));
        lb_Status.setText("Status");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lb_Tahun, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(lb_Merek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_Harga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_Nopolisi, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cb_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lb_Merek, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cb_Nopolisi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lb_Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lb_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lb_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 400, 410, 310);

        tb_sewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_sewa);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(450, 400, 890, 240);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jaz.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void jButtonprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonprintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonprintActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void txt_lamaSupirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lamaSupirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lamaSupirActionPerformed

    private void txt_lamaPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lamaPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lamaPinjamActionPerformed

    private void jButtonSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSewaActionPerformed
        create();
    
    }//GEN-LAST:event_jButtonSewaActionPerformed

    private void cb_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mobilActionPerformed
        // panel mobil
        String st = (String) cb_mobil.getSelectedItem();
        ResultSet rst = con.querySelectAll("tb_mobil", "tipe='" + st + "'");
//        ResultSet rst = con.eksekusiQuery("Select distinct tb_mobil where tipe='" + st + "'");
        if(cb_mobil.getItemCount()!=0)
        {
           try{
           String query="select nopol from tb_mobil where tipe='"+cb_mobil.getSelectedItem()+"'";
           ResultSet rsts = con.eksekusiQuery(query);
           cb_Nopolisi.removeAllItems();
           while(rsts.next())
           {
               cb_Nopolisi.addItem(rsts.getString("nopol"));
           }
           }catch(Exception e){
               
           }
           
        }
        else
        {
                    
        }
        try {
        
            while (rst.next()) {

                this.lb_Merek.setText(rst.getString("merek"));
                
                this.lb_Tahun.setText(rst.getString("tahun"));
                this.lb_Harga.setText(rst.getString("harga"));
                this.lb_Status.setText(rst.getString("status"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SewaMobil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cb_mobilActionPerformed

    private void cb_mobilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_mobilItemStateChanged
        // TODO add your handling code here:
//        if(cb_mobil.getItemCount()!=0)
//        {
//           try{
//               String query="select nopol from tb_mobil where tipe='"+cb_mobil.getSelectedItem()+"'";
//           ResultSet rsts = con.eksekusiQuery(query);
//           while(rsts.next())
//           {
//               cb_Nopolisi.addItem(rsts.getString("nopol"));
//           }
//           }catch(Exception e){
//               
//           }
//           
//        }
//        else
//        {
//                    
//        }
    }//GEN-LAST:event_cb_mobilItemStateChanged

    private void cb_NopolisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_NopolisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_NopolisiActionPerformed

    private void cb_SupirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_SupirActionPerformed
       String st = (String) cb_Supir.getSelectedItem();
        ResultSet rst = con.querySelectAll("tb_supir", "nama='" + st + "'");
        try {
            while (rst.next()) {

                //this.lbl_merek.setText(rst.getString("merek"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(SewaMobil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cb_SupirActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
       hitungselisih();
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SewaMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SewaMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SewaMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SewaMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SewaMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hitung;
    private javax.swing.JComboBox<String> cb_Nopolisi;
    private javax.swing.JComboBox<String> cb_Supir;
    private javax.swing.JComboBox<String> cb_mobil;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonSewa;
    private javax.swing.JButton jButtonprint;
    private com.toedter.calendar.JDateChooser jDatetglpeminjaman1;
    private com.toedter.calendar.JDateChooser jDatetglpengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_Harga;
    private javax.swing.JLabel lb_Merek;
    private javax.swing.JLabel lb_Status;
    private javax.swing.JLabel lb_Tahun;
    private javax.swing.JLabel lb_total;
    private javax.swing.JTable tb_sewa;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_lamaPinjam;
    private javax.swing.JTextField txt_lamaSupir;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nik;
    private javax.swing.JTextField txt_notelp;
    // End of variables declaration//GEN-END:variables

 private void loadMobil() {  // mengambil database

//        rs = con.querySelectAll("tb_mobil");
        String query="select distinct tipe from tb_mobil ";
        rs = con.eksekusiQuery(query);
        try {
            while (rs.next()) {
                cb_mobil.addItem(rs.getString("tipe"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(SewaMobil.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
 
 private void loadSupir() {  // mengambil database

        String query="select distinct nama from tb_supir ";
        rs = con.eksekusiQuery(query);
        try {
            while (rs.next()) {
                cb_Supir.addItem(rs.getString("nama"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(SewaMobil.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
 
 public void hitungselisih() {
         try {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String strDate1 = df.format(jDatetglpeminjaman1.getDate());
            String strDate2 = df.format(jDatetglpengembalian.getDate());
            Date Tanggal1 = df.parse(strDate1);
            Date Tanggal2 = df.parse(strDate2);
            long Hari1 = Tanggal1.getTime();
            long Hari2 = Tanggal2.getTime();
            long diff = Hari2 - Hari1;
            long Lama = diff / (24 * 60 * 60 * 1000);
            String Hasil = (Long.toString(Lama));
            txt_lamaPinjam.setText(Hasil);
            txt_lamaSupir.setText(Hasil);

            int harga_sewa = Integer.parseInt(lb_Harga.getText()); // lbl_harga di pars ke integer
            int lama_sewa = Integer.parseInt(txt_lamaPinjam.getText());   // txt_lama di pars ke integer
            int harga_supir = Integer.parseInt(txt_lamaSupir.getText());
            int Total = (harga_sewa * lama_sewa) + (100000 * harga_supir) ;                     // mencari total Harga
            String a = Integer.toString(Total);
            lb_total.setText(a);



        } catch (Exception a) {
            JOptionPane.showMessageDialog(this, "Masukan Tanggal Peminjaman dan Tanggal Pengembalian");
        }
    }
 
 private void loadTabel() {
        String namaKolom[] = {"Nama", "No_telp", "Tipe_mobil", "No_polisi", "harga","Tgl_peminjaman","Tgl_pengembalian","Lama_mobil", "Supir","Lama_supir","Total"}; //,
        rs = con.querySelect(namaKolom, "sewa_mobil");
        tb_sewa.setModel(new ResultSetTable(rs)); //,"tgl_pinjam","tgl_kembali" ,jDateChooser1.getDateFormatString(),jDateChooser2.getDateFormatString()
    }
 
 private void create() {
        try {

            if ( !txt_nik.getText().isEmpty() && !txt_nama.getText().isEmpty() && !txt_alamat.getText().isEmpty() && !txt_notelp.getText().isEmpty()) {

                if (!jikakeluar()) {

                    JOptionPane.showMessageDialog(this, "maaf mobil ini sedang tidak tersedia");
                } else {
                    java.util.Date tgl = (java.util.Date) this.jDatetglpeminjaman1.getDate();
                    java.util.Date tgl1 = (java.util.Date) this.jDatetglpengembalian.getDate();
                    String kolom[] = {"NIK","Nama","Alamat", "No_telp","Tipe_mobil","No_polisi","Harga", "Tgl_peminjaman", "Tgl_pengembalian","Lama_mobil","Supir","Lama_supir", "Total"};
                    String isi[] = {txt_nik.getText(),txt_nama.getText(),txt_alamat.getText(),txt_notelp.getText(),cb_mobil.getSelectedItem().toString(),cb_Nopolisi.getSelectedItem().toString(),lb_Harga.getText(),new java.sql.Date(tgl.getTime()).toString(),new java.sql.Date(tgl1.getTime()).toString(),txt_lamaPinjam.getText(),cb_Supir.getSelectedItem().toString(),txt_lamaSupir.getText(),lb_total.getText()};
                    
                    System.out.println(con.queryInsert("sewa_mobil", kolom, isi));
                   
                    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
                    cekstatus();
                   
                }


            } else {
                JOptionPane.showMessageDialog(this, "Data isian ada yang kosong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error input data");
            System.out.println("salah");
        }
        loadTabel();
        clear();
    }
 
 private void clear() {
        lb_total.setText("");
        txt_lamaPinjam.setText("");
        // boxnopol.addItem(rs.getString("nopol"));
        //jDateChooser1.addNotify();
        //jDateChooser2.addNotify();
    }

    public void cekstatus() throws SQLException {
        rs = con.querySelectAll("tb_mobil", "nopol ='" + cb_Nopolisi.getSelectedItem().toString() + "'");
        while (rs.next()) {
            status1 = rs.getString("status");

        }
        String update_status = "Keluar";
        String kolom[] = {"status"};
        String isi[] = {update_status};
        con.queryUpdate("tb_mobil", kolom, isi, "nopol='" + cb_Nopolisi.getSelectedItem().toString() + "'");



    }

    public boolean jikakeluar() throws SQLException {
        boolean hasil;

        rs = con.querySelectAll("tb_mobil", "nopol ='" + cb_Nopolisi.getSelectedItem().toString() + "'");
        while (rs.next()) {
            status1 = rs.getString("status");
        }
        if (status1.equals("Keluar")) {
            hasil = false;
        } else {
            hasil = true;
        }
        return hasil;

    }


}
